void ghost(bool atas, bool bawah,bool kiri,bool kanan);
void level(int l);
void tempMaps(int temp, int baris, int kolom);
void move(bool atas, bool bawah, bool kiri, bool kanan);
void limit();
void ceksprite(int sprite, int baris, int kolom);
void pointt();
void tempp();
void movement(int l);
void maping();
void next_level();
void die();
int num_level(int l);
void save(char* name, int l);
void leaderboard();
void Sort_file();
void menu_utama();
void timers(clock_t dur_h, clock_t dur_m,clock_t dur_s);
void pilihan();
void limitghost();
