int maps_level(int l, int a, int b);
void maps(int mat, int baris, int kolom);
void diamond(int mat, int baris, int kolom);

void black(int i, int j);
void block(int i, int j);
void block2(int i, int j);
void stblock(int i, int j);
void stairs(int i, int j);
void rope(int i, int j);
void diamond(int i, int j);
void door(int i, int j);
void panto(int i, int j);
void boom(int i, int j);
void sp_fall(int i, int j);
void hook(int i, int j, int p);
void run(int i, int j, int p);
void naik(int i, int j, int p);
void climb(int i, int j, int p);
void img_bomb(int i, int j, int p);
void how();
void keluar();
